spring:
# db
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
user:
  dir: F:\project\mybatis-plus

logging:
  level:
    com:
      example:
        demo:
          dao: debug


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true
  type-aliases-package: com.example.demo.entity